# Generated by Django 5.2 on 2025-04-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=8.45, max_length=254),
            preserve_default=False,
        ),
    ]
