# Generated by Django 5.2 on 2025-04-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_roombooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=20, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('topic', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('approved', 'อนุมัติ'), ('pending', 'รออนุมัติ'), ('cancelled', 'ยกเลิก')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
