# Generated by Django 5.2 on 2025-04-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_delete_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
