# Generated by Django 5.2 on 2025-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_booking_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('approved', 'อนุมัติ'), ('pending', 'รออนุมัติ'), ('cancelled', 'ยกเลิก')], default='approved', max_length=20),
        ),
    ]
