# Generated by Django 5.2 on 2025-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dpm_sd',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='h_pr',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='n_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='n_list',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='n_ph',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='n_req',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
