# Generated by Django 5.2 on 2025-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_booking_dpm_sd_booking_h_pr_booking_n_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
