# Generated by Django 5.2 on 2025-04-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_holiday_booking_equipment_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='equipment_list',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment_list',
            field=models.ManyToManyField(blank=True, to='myapp.equipment'),
        ),
    ]
